#!/bin/sh
LAUNCHER=$(readlink -f "${0}")
HERE="$(dirname "${LAUNCHER}")"
cd "${HERE}/../lib/smath" || exit 1
VERSION="$(cat "${HERE}/../../VERSION")"

# Run SMath
mono --debug SMathStudio_Desktop.exe "$@"
${HERE}/restore-environment.sh

# Show a crash dialog if something went wrong
if [ $? != 0 ] && [ $? != 1 ]; then
	LOGS="${XDG_CONFIG_HOME:-${HOME}/.config}/SMath/Logs"
	if [ ! -d "${LOGS}" ] && [ -d "${HOME}/.SMath/Logs" ]; then
		LOGS="${HOME}/.SMath/Logs"
	fi

	test -d Support/Logs && LOGS="${PWD}/Support/Logs"
	ERROR_MESSAGE="SMath has encountered a fatal error.\nPlease refer to the crash logs and FAQ for more information.\n\nLog files are located in ${LOGS}\n"
	if command -v zenity > /dev/null; then
		zenity --no-wrap --error --title "SMath" --text "${ERROR_MESSAGE}" 2> /dev/null
	elif command -v kdialog > /dev/null; then
		kdialog --title "SMath" --error "${ERROR_MESSAGE}"
	elif "${HERE}/gtk-dialog.py" test > /dev/null; then
		"${HERE}/gtk-dialog.py" error --title "SMath" --text "${ERROR_MESSAGE}" 2> /dev/null
	else
		printf "${ERROR_MESSAGE}\n"
	fi
	exit 1
fi
