#!/bin/sh
HERE="$(dirname "${LAUNCHER}")"
# Run SMath
exec MONO_PATH="${HERE}/../lib/mono/4.5" MONO_CFG_DIR="${HERE}/../../etc" MONO_CONFIG="${HERE}/../../etc/mono/config" "${HERE}/mono" "${HERE}/../lib/smath/SMathStudio_Desktop.exe" "$@"
